In [1]:
# Setup: install the checker and download the public tests (run this cell first)
%pip install -q otter-grader==7.0.0

import os, urllib.request
TESTS_URL = "https://raw.githubusercontent.com/NaiveNeuron/ml_exercises/master/assignment1/tests/"
os.makedirs("tests", exist_ok=True)
for q in ["q1_reshape", "q2_mean", "q4_zero_every_second", "q5_set_lower", "q6_average", "q7_linear_loops", "q8_linear_vectorized", "q9_sliding_window"]:
    path = os.path.join("tests", q + ".py")
    if not os.path.exists(path):
        urllib.request.urlretrieve(TESTS_URL + q + ".py", path)

import otter
grader = otter.Notebook()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.1/140.1 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.2/119.2 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.1/88.1 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 71.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 57.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 MB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.8/623.8 kB 15.3 MB/s eta 0:00:00


 ## Introduction to numpy

As the title says, welcome to this introductory notebook where we will try to learn something about `numpy`.

Throughout this notebook you will be asked to solve exercises. Each of them is marked with a heading such as

<h5 style="color: #1B1BFF">Exercise 1</h5>

and followed by a `grader.check(...)` cell (for instance, `grader.check("q1_reshape")` checks Exercise 1).

------------------------------

Writing clean vectorized `numpy` code is in many cases essential. Familiarity with this tool will help you write code that is both elegant and efficient and thus leads into faster and more effective experiemnts. Much more importantly, however, it will become easier for you to rewrite matematical equations because your code **will read like equations**. So lets start with some basics.

### Grading

This tutorial is worth up to **10 points** towards your semester grade (see the [course info](https://compbio.fmph.uniba.sk/vyuka/ml/info.php)). You get the points only if you complete **all exercises** in this notebook (Exercises 1 to 9), including the final question at the end (Exercise 9). Solving only the final question earns no points.

After each exercise you will find a `grader.check(...)` cell. Run it to check your answer against basic tests. Passing these checks does not guarantee the points: when grading, we run additional tests.

In [2]:
import numpy as np

First, the imports. While it is not strictly required, most of the time you will find `numpy` to be imported as `np`. We suggest you do the same in your own projects/scripts.

If you would want to create a vector `a` in `numpy` you can do so as follows:

In [3]:
a = np.array([2, 4, 5, 6])
print(a)

[2 4 5 6]


To create a matrix you can use same syntax as you would for 2D arrays in Python

In [4]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
print(A)

[[1 2 3 4]
 [5 6 7 8]]


Through this tutorial, we will try to keep the names of vectors (which will be lower-case) and matricies (which will
be keep upper-case) constant.

Since we now know how to create basic numpy objects, lets talk about them a bit.

All objects like these (vector, matrix...) have a **shape** attribute which describes, as the name suggests, their shape. In other words, it descibes what do the dimensions of a particular object look like. This attribute can be accesed by typing `.shape` after the name of the object.

Here are some examples:

In [5]:
# create a vector
a = np.array([1, 2, 3, 4])
print("{}\n".format(a))

# create a 2D matrix
A = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4]])
print("{}\n".format(A))

# create 3D matrix (literally a 3D Python array wrapped in np.array)
B = np.array([[[1, 2], [1, 2],
               [3, 4], [3, 4]],
              [[4, 5], [5, 6],
               [4, 5], [5, 6]]])
print("{}\n".format(B))

# print shapes of all create objects
print("Shape of vector a is {}".format(a.shape))
print("Shape of matrix A is {}".format(A.shape))
print("Shape of matrix B is {}".format(B.shape))

[1 2 3 4]

[[1 2 3 4]
 [1 2 3 4]]

[[[1 2]
  [1 2]
  [3 4]
  [3 4]]

 [[4 5]
  [5 6]
  [4 5]
  [5 6]]]

Shape of vector a is (4,)
Shape of matrix A is (2, 4)
Shape of matrix B is (2, 4, 2)


Throughout this course we will mostly work with high dimensional objects.

In scientific computation practice, it is often needed to create a multidimensional object with certain values, such as an array with all elements equal to zero or a matrix initialized with values sampled from the normal distribution.

Luckilly, `numpy` is awesome in this regard, as it provides readily-available solutions to pretty much all of the "standard needs". If you feel like "someone must have done this before", chances are there is a `numpy` function for it.

Here are some examples of usage of functions for matrix and array creation that you may find useful:

In [6]:
# creates a vector with elements [0, 1, 2, 3, 4]
a = np.arange(5)
print("a = {}".format(a))

# we can also set its starting point. So to create vector [10, 11, 12, 13, 14]
# we would do
v = np.arange(10, 15)
print("v = {}".format(v))

# and also we can set step size. So to create a vector with elements spaced by 10
# with start at 10 and end at 40, that is [10, 20, 30, 40] we would do
u = np.arange(10, 50, 10)
print("u = {}".format(u))

# Create a matrix filled with zeros of shape (10, 5)
A = np.zeros((10, 5))
print("A =")
print(A)

# Create a matrix filled with ones of shape (5, 10)
B = np.ones((5, 10))
print("B =")
print(B)

a = [0 1 2 3 4]
v = [10 11 12 13 14]
u = [10 20 30 40]
A =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
B =
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [7]:
# Create a 2D matrix with random values of shape (5, 5)
X = np.random.rand(5, 5)
print("X with shape {}".format(X.shape))
print(X)

# Create 3D matrix with values sampled from normal distribution of shape (2, 3, 2)
Y = np.random.randn(2, 3, 2)
print("\nY with shape {}".format(Y.shape))
print(Y)

X with shape (5, 5)
[[0.17883271 0.94594525 0.62308456 0.7572573  0.6529005 ]
 [0.43160317 0.21739548 0.19850002 0.59573406 0.89383876]
 [0.29497805 0.95412586 0.22783232 0.76032458 0.68367015]
 [0.83817279 0.41755024 0.25248447 0.38299649 0.15878948]
 [0.19107723 0.55902044 0.19330005 0.70545342 0.95876455]]

Y with shape (2, 3, 2)
[[[-1.33552069  0.02933592]
  [ 0.03122673  0.50356329]
  [ 0.80254479 -1.54414204]]

 [[ 0.48541287 -0.11099061]
  [-0.26021365 -0.70333197]
  [-1.90736485  0.96620664]]]


Once we have these objects initalized, there are a ton of aritmetic operations we can do with them:

In [8]:
a = np.array([1, 2, 3, 4, 5])
print("a = {}".format(a))

# add a constant value to each element of a vector
print("a + 5 = {}".format(a + 5))

# multiply each element of a vector by a constant value
print("a * 5 = {}".format(a * 5))

# square the vector a
print("a^2 = {}".format(a ** 2))

v = np.array([2, 2, 3, 2, 3])
print("v = {}".format(v))

# multiply vector a by  vector v
print("a * v = {}".format(a * v))

a = [1 2 3 4 5]
a + 5 = [ 6  7  8  9 10]
a * 5 = [ 5 10 15 20 25]
a^2 = [ 1  4  9 16 25]
v = [2 2 3 2 3]
a * v = [ 2  4  9  8 15]


To multiply matrices together (to get their **element-wise** or [Hadamard](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) product, not the **dot product**), we do not need to do anything special:

In [9]:
A = np.array([[1, 2, 3],
              [1, 2, 3]])
B = np.array([[2, 2, 2],
              [3, 3, 3]])
print("A =\n{}".format(A))
print("B =\n{}".format(B))
print("")
print("A * B =\n{}".format(A * B))

A =
[[1 2 3]
 [1 2 3]]
B =
[[2 2 2]
 [3 3 3]]

A * B =
[[2 4 6]
 [3 6 9]]



We can also do other standard matrix operations with `numpy`, such as **dot product**.

In [10]:
A = np.random.rand(2, 3)
print("A with shape {}\n".format(A.shape))
print(A)
B = np.random.randn(3, 5)
print("B with shape {}\n".format(B.shape))
print(B)
print("\nA \dot B =")
# dot product of 'A' and 'B' to create a tensor of size (2, 5)
print(A.dot(B))

A with shape (2, 3)

[[0.51909489 0.67726929 0.43628621]
 [0.15865374 0.75121402 0.89905134]]
B with shape (3, 5)

[[ 0.18565512  0.84765419 -0.99714874  1.34783636 -0.79260498]
 [-1.30101942 -0.06206547  1.04510379  1.03332847  1.73997605]
 [-0.99248024  0.83147887  1.31541887 -1.8711615   0.82790636]]

A \dot B =
[[-1.21777332  0.76074069  0.764101    0.58313464  1.12819928]
 [-1.84017983  0.83540124  1.80952434 -0.69218014  1.92567497]]


<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1068/1997926889.py:7: SyntaxWarning: invalid escape sequence '\d'
  print("\nA \dot B =")


Oftentimes your vectors/matricies will have a shape that is just not what you would want.

For instance, your data can be (and often times will be) stored in a common data storing formats like CSV. These formats are easily loadable with Python but not very usefull, since our models will almost certainly require vectors or matricies of certain shape. To reshape our vectors/matricies, numpy provides a `.reshape` function.

For example, suppose we would find interesting data that consits of 100 gray scale images each having `36 x 36`px and loaded it into our Python environment. Note that since these are grayscale images, each pixel is represented as a single scalar value.

Long story short, our matrix would have shape `(100, 36, 36)`. Now, we would like to use this to train some model. But our model takes a vector, not a matrix. We can easily preprocess this data accordingly with `numpy`.

In [11]:
# loaded matrix
X = np.random.randn(100, 36, 36)

# print shape of matrix X
print("Shape of a matrix X is {}\n".format(X.shape))

# reshape matrix X to contain 100 vectors
Y = np.reshape(X, (100, 36 * 36))

# print shape of new matrix Y
print("Shape of new reshaped matrix Y is {}".format(Y.shape))

Shape of a matrix X is (100, 36, 36)

Shape of new reshaped matrix Y is (100, 1296)


-------------------------------

<h5 style="color: #1B1BFF">Exercise 1</h5>

Reshape vector X, such that after the reshape operation it will contain 100 examples -- each of those with dimensions 240, 240, 3. Store the reshaped array in `X_reshaped`.

In [15]:
X = np.random.randn(17280000)

# RESHAPE HERE
X_reshaped = np.reshape(X, (100, 240, 240, 3))

print("New reshape vector X with shape: {}".format(X_reshaped.shape))

New reshape vector X with shape: (100, 240, 240, 3)


In [16]:
grader.check("q1_reshape")

q1_reshape results: All test cases passed!

------------------------------------------

You may also often times need to find the `sum` or `mean` of a vector or a matrix.

For all operations like this `numpy` already provides an implemented function (`mean`, `sum`, ...). These functions can also take an optional `axis` argument, which specifies in which axis should an operation be executed.

For instance, if we would like to take a sum of the first axis of vector `x` we would do something like `np.sum(x, axis=0)` (dimension are indexed from zero).

In [17]:
# create some matrix x
X = np.array([[1, 3, 5, 7],
              [6, 7, 3, 1],
              [1, 4, 5, 1],
              [7, 8, 4, 3],
              [1, 2, 3, 4],
              [9, 5, 4, 3],
              [9, 8, 7, 6]])
print("Shape of X: {}\n".format(X.shape))

# take sum of first axis
s = np.sum(X, axis=0)
print("sum of first dimension of matrix x: \ns={}\n".format(s))

print("Shape of s: {}".format(s.shape))

Shape of X: (7, 4)

sum of first dimension of matrix x: 
s=[34 37 31 25]

Shape of s: (4,)


-------------------------------

<h5 style="color: #1B1BFF">Exercise 2</h5>

Find the mean of the matrix `Z` in the second dimension and store it in `Z_mean`. Furthermore, store the dimensions of this resulting matrix in `Z_mean_shape` (we print them for you).

In [22]:
Z = np.random.rand(10, 10, 15)

## Mean of the Z matrix in the second dimension:
Z_mean = np.mean (Z, axis=1)

## Dimensions of the result
Z_mean_shape = Z_mean.shape
print(Z_mean_shape)

(10, 15)


In [23]:
grader.check("q2_mean")

q2_mean results: All test cases passed!

<!-- BEGIN QUESTION -->

<h5 style="color: #1B1BFF">Exercise 3</h5>

How would dimensions change if we would have taken the mean of the last (third) axis? Please also *briefly* explain what would the output of the `mean` operation represent if we changed the `axis` parameter.

Write your answer into the `q3_answer` string in the cell below.

In [25]:
# Write your answer as plain text between the triple quotes.
q3_answer = """
Instead of doing the mean of the columns and reduce the rows in one unit (mean of the columns) it will do the mean of the rows and reduce the columns in one unit (the mean of the rows).
The selected axis is the dimension that will be reduced."""

<!-- END QUESTION -->

---------------------------------------

`numpy` also supports an operation called **broadcasting**. This can be better explained on some example.
Let us assume we have a 2D matrix with 10 training examples, each of them having 3 features (matrix `X` of shape (10, 3)). Further suppose we also have a vector `w` of weights for each feature of size `(3, )`.

Now, we would like to weigh each one of our traning examples with our wieght vector `w`. In plain Python we would probably have to write 2 `for` loops. With `numpy` it seems that since we can multiply vectors, we could probably make do with just one.

Thankfully, all of this has been taken care of for us by **broadcasting**. In the end, all we need is a simple multiplication:

In [24]:
# create random weight vector w
w = np.random.randn(3)
print("w with shape {}".format(w.shape))
print(w)

# create random matrix X
X = (np.random.rand(10, 3) * 10) + 3
print("X with shape {}".format(X.shape))
print(X)
print("")

# multiply each vector of shape (3,) in a second
# dimension of matrix X by weight vector w
print("Multiplication result:")
print(X * w)

w with shape (3,)
[-1.34980113 -1.24940121  0.56985893]
X with shape (10, 3)
[[10.17709712 12.35703949  5.60274457]
 [11.01684966  3.51891153  7.51815177]
 [ 4.40254926  8.95316449  3.22233576]
 [ 3.31955534  5.73879983  8.80594452]
 [ 7.65529819  9.28470111 12.93059132]
 [12.25937802  7.4906358  12.41272984]
 [ 7.16335003  5.13629946  7.19773896]
 [10.64382798 12.64070907  3.73681696]
 [ 9.33439873  4.24253098  3.1000385 ]
 [ 5.72798048  9.8988569   3.10030905]]

Multiplication result:
[[-13.73705723 -15.43890003   3.192774  ]
 [-14.87055617  -4.39653231   4.2842859 ]
 [ -5.94256598 -11.1860945    1.83627679]
 [ -4.48073956  -7.17006343   5.01814609]
 [-10.33313017 -11.60031675   7.36861289]
 [-16.54772236  -9.35880939   7.0735049 ]
 [ -9.669098    -6.41729874   4.1016958 ]
 [-14.36705108 -15.79331715   2.1294585 ]
 [-12.59958199  -5.30062332   1.76658461]
 [ -7.73163455 -12.36764374   1.76673879]]


If we would want to set all elements in the second dimension of the first element of some matrix to zero, we can also do so with `numpy`s broadcasting by simply typing **:** instead of a number in a specific dimension.

*Note*: the magical colon **:** here is actually the delimeter -- part of the syntax for "slicing" Python sequences (of any kind, really). For instance,

- `[1:5]` is equivalent to saying "from 1 to 5"
- `[:5]` is equivalent to saying "from beginning to 5"
- `[1:]` is equivalent to saying "from 1 to end"

Taking all of this into consideration, in the end we get `[:]` which can be equivalently described as "from beginning to end"

In [26]:
# create random matrix X
X = np.random.randn(4, 3)
print("X =\n{}".format(X))
print("")

# set all elements of a first dimension to zero
X[0, :] = 0

print("X =\n{}".format(X))

X =
[[ 0.84837999  0.6648809   1.31872103]
 [-1.57880244 -0.27961813  2.84959422]
 [ 0.57161625  0.7251676   0.07578753]
 [ 0.47276459  1.62658428  0.70497438]]

X =
[[ 0.          0.          0.        ]
 [-1.57880244 -0.27961813  2.84959422]
 [ 0.57161625  0.7251676   0.07578753]
 [ 0.47276459  1.62658428  0.70497438]]


`numpy` also supports indexing by specifying a vector of indexes and then passing it to a "sliceable" object (i.e. matrix or vector). Or you can also specify a boolean matrix/vector (in other words a *mask*) and pass it to any object of this sort. Values in places with `True` value will be picked up while values on `False` places will be ignored.

In [27]:
# create matrix X filled with ones
X = np.ones((4, 3))
print("X =\n{}\n".format(X))

# create vector of indecies for matrix X
idx = [0, 3]
X[idx] = 0
print("After running X[idx] = 0")
print("X =\n{}\n".format(X))

# create boolean matrix to select only certain values
bool_idx = np.zeros((4, 3)).astype('bool')
bool_idx[2, 2] = True
bool_idx[3, 2] = True
bool_idx[1, 0] = True
print("bool_idx =\n{}\n".format(bool_idx))

# set each values specified in bool_idx to 300
X[bool_idx] = 300
print("After running X[bool_idx] = 300")
print("X =\n{}".format(X))

X =
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

After running X[idx] = 0
X =
[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]

bool_idx =
[[False False False]
 [ True False False]
 [False False  True]
 [False False  True]]

After running X[bool_idx] = 300
X =
[[  0.   0.   0.]
 [300.   1.   1.]
 [  1.   1. 300.]
 [  0.   0. 300.]]


These operations are usually heavily optimized in the background, so in most cases it is worth writing **vectorized** code with `numpy` rather than loops (even if it may take some time to figure out how to actually do that).

We can also compare values in numpy arrays. Comparing an array or a matrix with some value will return an array or a matrix of the same shape but with boolean values. If the value in a certain position meets the specified condition, the resulting matrix will have `True` value in that position. If it does not meet the condition, it will be `False`.

In [28]:
# create matrix X
X = np.array([[1, 4, 3, 5],
              [1, 2, 3, 7],
              [5, 6, 2, 7]])
print("X =\n{}\n".format(X))

# get all values that are more than 3
print("X > 3 =\n{}".format(X > 3))

X =
[[1 4 3 5]
 [1 2 3 7]
 [5 6 2 7]]

X > 3 =
[[False  True False  True]
 [False False False  True]
 [ True  True False  True]]


As we can see, this nicely combines with what we learned before on `numpy`'s support for indexing by a boolean array/matrix. So if we want to set all the values that are bigger than `3` to say `300`, we can just do:

In [29]:
print("X =\n{}\n".format(X))

# get all values that are more than 3
bool_idx = X > 3
print("X > 3 =\n{}".format(bool_idx))

# set all those values to 300
X[bool_idx] = 300
print("X =\n{}\n".format(X))

X =
[[1 4 3 5]
 [1 2 3 7]
 [5 6 2 7]]

X > 3 =
[[False  True False  True]
 [False False False  True]
 [ True  True False  True]]
X =
[[  1 300   3 300]
 [  1   2   3 300]
 [300 300   2 300]]



-------------------------------

<h5 style="color: #1B1BFF">Exercise 4</h5>

Create random array of shape (10, 10, 3) that will have every second element (starting with index 1) in the second dimension set to zero. Store it in `R`.

In [44]:

R= np.random.rand(10, 10, 3)
R[:, 1::2, :]=0
print (R)
print(R.shape)


[[[0.66392952 0.38271035 0.33561335]
  [0.         0.         0.        ]
  [0.76164525 0.63963131 0.92177802]
  [0.         0.         0.        ]
  [0.33419549 0.48064    0.14712002]
  [0.         0.         0.        ]
  [0.73957016 0.74466233 0.03476684]
  [0.         0.         0.        ]
  [0.99243152 0.80011134 0.22321671]
  [0.         0.         0.        ]]

 [[0.84427577 0.53126039 0.33652148]
  [0.         0.         0.        ]
  [0.73089568 0.48443411 0.59844152]
  [0.         0.         0.        ]
  [0.41274616 0.15223852 0.91866015]
  [0.         0.         0.        ]
  [0.34100804 0.49387707 0.28652815]
  [0.         0.         0.        ]
  [0.36103578 0.14429363 0.04823712]
  [0.         0.         0.        ]]

 [[0.84944839 0.96691725 0.46576725]
  [0.         0.         0.        ]
  [0.34865229 0.83925079 0.90191691]
  [0.         0.         0.        ]
  [0.7006355  0.97071782 0.57541147]
  [0.         0.         0.        ]
  [0.77342494 0.55339163 0.3749310

In [45]:
grader.check("q4_zero_every_second")

q4_zero_every_second results: All test cases passed!

<h5 style="color: #1B1BFF">Exercise 5</h5>

Create a function that will set all the elements of a given array/matrix under a specified threshold to a specific value (we prepared the function header for you). The function should modify the given array in place.

In [52]:
def set_lower(X, thresh, value):
    bool_idx = X < thresh
    X[bool_idx]=value


X = np.array([[1, 3, 5],
              [3, 5, 1],
              [1, 2, 5]])
set_lower(X, 3, 5000)
print("X =\n{}".format(X))

Y = np.random.randn(100, 100, 100)
set_lower(Y, 0.5, 1)

X =
[[5000    3    5]
 [   3    5 5000]
 [5000 5000    5]]


In [53]:
grader.check("q5_set_lower")

q5_set_lower results: All test cases passed!

------------------------------------------

**And much more...** if you are iterested, all operations can be found in the [**offical documentation**](https://docs.scipy.org/doc/numpy/contents.html).

Furthermore, if you would like to familiarize yourself with `numpy` even more, we suggest you take a look at the [**Numpy Excercises**](https://github.com/Kyubyong/numpy_exercises).


Now for the fun part of this excercise.


We'll import some helper functions first and get right back to the excercises.

In [54]:
import time
import functools
from matplotlib import pyplot as plt


def timeit(func):
    """
    Profiling function to measure time it takes to finish function.

    Args:
        func(*function): Function to meassure

    Returns:
        (*function) New wrapped function with meassurment
    """
    @functools.wraps(func)
    def newfunc(*args, **kwargs):
        start_time = time.time()
        out = func(*args, **kwargs)
        elapsed_time = time.time() - start_time
        ftime = elapsed_time
        msg = "function [{}] finished in {} ms"
        print(msg.format(func.__name__, ftime))
        return out
    return newfunc


def show_cut_image(x):
    f, axarr = plt.subplots(4, 4)
    rnd = x[np.random.randint(x.shape[0], size=16)]
    for i in range(4):
        for j in range(4):
            axarr[i, j].imshow(rnd[i + j * 4])
            axarr[i, j].axis('off')
    plt.show()


------------------

<h5 style="color: #1B1BFF">Exercise 6</h5>

Rewrite this matematical equation first with the use of loops and then as functional vectorized numpy code:

$$y = \frac{1}{n}\sum_i^n{X_i}$$

In [57]:
X = np.arange(50)

def operate_loops_avg(X):
    y=0
    for i in range(X.size):
      y += X[i]
    y = y/X.size
    return y

operate_loops_avg(X)

np.float64(24.5)

In [58]:
X = np.arange(50)

def operate_vectorized_avg(X):
    y = np.mean(X)
    return y

operate_vectorized_avg(X)

np.float64(24.5)

In [59]:
grader.check("q6_average")

q6_average results: All test cases passed!

<h5 style="color: #1B1BFF">Exercise 7</h5>

Rewrite this matematical equation with the use of `for` loops. Please use the prepared function header.

$$y = \sum_j \sum_n \big(\sum_m X_{j,m} \cdot W_{m,n}\big) + b_{n}$$

where $b$ is a vector, $X_j$ is an input vector for the example $j$ and $W$ is a weight matrix.

In [ ]:
A = np.random.rand(10, 100)
B = np.random.rand(100, 100)
c = np.random.rand(100)

@timeit
def operate_loops(X, W, b):
    y = 0
    return y

for x in range(10):
    operate_loops(A, B, c)

In [ ]:
grader.check("q7_linear_loops")

<h5 style="color: #1B1BFF">Exercise 8</h5>

Now write the same equation but as numpy vectorized code. Difference between results of these two functions should be **zero** or **very close to zero**.

In [ ]:
@timeit
def operate_vectorized(X, W, b):
    y = ...
    return y

for x in range(10):
    operate_vectorized(A, B, c)

# print("Difference: {}".format(np.sum(np.abs(operate_vectorized(A, B, c) - operate_loops(A, B, c)))))

In [ ]:
grader.check("q8_linear_vectorized")

As you can see, the `numpy` vectorized code runs much faster. This is due to the fact that vectorized operations, broadcasting and native `numpy` functions are heavily optimized to run as eficiently as possible.

------------------------------------------------------------------------------------------------------------------

### Final question (Exercise 9):

We loaded a picture for you in the cell below. With just reshape and function `moveaxis()` (check out the offical docs) split the image into equal chunks. In other words, simulate sliding window cutter that will cutout window of size `80 x 80` each **80 pixels**. Your final array should have shape `108 x 80 x 80 x 3`. This should not take more than few lines of code. You can also pass the final array to `show_cut_image(<your array here>)` function to see some of your cutouts. Store the result in `cuts`.

In [ ]:
from scipy import datasets
import skimage.transform
import matplotlib.pyplot as plt

img = datasets.face()
img = skimage.transform.resize(img, (720, 960))
plt.imshow(img)
plt.show()

print("Image shape: {}".format(img.shape))

In [ ]:
# RESHAPE AND ROLL HERE
cuts = ...
# show_cut_image(cuts)

In [ ]:
grader.check("q9_sliding_window")

### Submission details


*Remember: the points require completing the whole notebook, including the final question (see **Grading** at the top of this notebook).*

*If you need any help with this assignment, please feel free to ask the course TAs during their office hours, which can be found at the [course website](http://compbio.fmph.uniba.sk/vyuka/ml/).*


## This is all for now. Thank you!